### ISSUE TITLE
Reimplement !lastreplay

### ISSUE THREAD

**Issue by chrsin** [FAForever/faf-qai#11] opened 2020-11-21 12:20 UTC

**Comment by FemtoZetta** [comment] 2020-11-22 00:52
This is how it worked before: 
![grafik](https://user-images.githubusercontent.com/61892809/99890991-00af4800-2c5d-11eb-8e15-ada635127b0a.png)

When it didn't find a replay it just said "Replay not found."

**Comment by Soyvolon** [comment] 2020-11-22 03:27
Duplicate of #9

**Closed by Soyvolon** 2020-11-22 03:27 UTC
